### ISSUE TITLE
Auto Export google sheets files

### ISSUE THREAD

**Issue by skehoe3** [skehoe3/corona_solutions#13]
Figure out how to auto export the new data-- the google sheets files are our temporary quick and dirty database

**Comment by krasswez** [comment]
This is done. https://developers.google.com/sheets/api/quickstart/python provides basically all you need to know.

- Need to provide the spreadsheet ID

- A credentials.json file for the spreadsheet is required - we get that, when we enable the Google API for the spreadsheet

- also works with Python3 (checked that)

- For sample range, just provide the columns (e.g. "A:M")

- On first run, need to verify access in browser
